use_frameworks!

platform :ios, '9.0'

target 'TutSKImageExtension_Example' do
  pod 'TutSKImageExtension', :path => '../'

  target 'TutSKImageExtension_Tests' do
    inherit! :search_paths

    
  end
end
